Added check user input dialogs

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,14 +1,13 @@
 #!/bin/bash
 
-# Переменные
-MYHOST="AcerOne"
-MYUSER="victor3d"
-
 echo "Quick and dirty install of awesome Arch Linux"
 echo "Before you START, do partitioning and mount root filesystem to /mnt"
 read -p "Let the magic begin..."
-
-set -xe
+while [[ $MYHOST1 == '' ]]
+do
+    read -p "Hostname: " MYHOST1
+done
+MYHOST=$(echo $MYHOST1 | tr -cd [:alnum:])
 
 system_identify()
 {
@@ -84,9 +83,13 @@ sed -i '1 i\Server = http://mirror.yandex.ru/archlinux/$repo/os/$arch' /etc/pacm
 pacman-key --init
 pacman-key --populate archlinux 
 pacman-key --refresh-keys
+
+set -xe
  
 # Установим базовые пакеты системы.
 pacstrap -i /mnt base base-devel $UCODE netctl dialog wpa_supplicant wget reflector nfs-utils net-tools rsync sudo git wget yajl xorg-server xorg-xinit gtk-engine-murrine mesa-libgl xterm mesa lightdm lightdm-gtk-greeter xcompmgr xf86-video-intel autoconf2.13 yasm gconf conky lxappearance geany ttf-liberation ttf-dejavu opendesktop-fonts ttf-bitstream-vera ttf-arphic-ukai ttf-arphic-uming ttf-hanazono gtk-engine-murrine cbatticon oblogout xf86-input-synaptics lxterminal transmission-gtk filezilla libva-intel-driver i3lock scrot imagemagick xautolock mcabber mpv htop dmenu xfce4-screenshooter pulseaudio pulseaudio-alsa procmail poppler lynx mutt terminator alsa-utils moc gmrun tint2 feh acpi mc nano cdparanoia cdrkit p7zip unrar zip openssh openbox obconf faenza-icon-theme tangerine-icon-theme pcmanfm file-roller gvfs gnome-menus ntfs-3g dosfstools exfat-utils xbindkeys networkmanager network-manager-applet hicolor-icon-theme gpicview volumeicon truecrypt keepassxc ranger i3-wm i3lock i3blocks i3status xorg-xkill terminus-font gtk-theme-switch2 redshift surf zathura links atool bind-tools cmake compton cronie f2fs-tools ffmpegthumbnailer gpart gparted gperf gsimplecal libreoffice-fresh libreoffice-fresh-ru mediainfo mtools mupdf namcap ncdu nmap newsboat ntp odt2txt pass pkgfile qt5ct rpmextract ttf-font-awesome udftools w3m weechat whois youtube-dl firefox-i18n-ru firefox firefox-adblock-plus gsfonts --noconfirm
+
+set +xe
 
 # Генерируем fstab, используя следующую команду:
 genfstab -p /mnt >> /mnt/etc/fstab
@@ -170,11 +173,51 @@ mkdir /mnt/etc/skel/.config/volumeicon
 curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/volumeicon/volumeicon > /mnt/etc/skel/.config/volumeicon/volumeicon
 
 echo "!!! Установка пароля для ROOT"
-arch-chroot /mnt /bin/bash -c "passwd"
+
+while [[ $ROOTPASS1 == '' ]] || [[ $ROOTPASS2 == '' ]] || [[ $ROOTPASS1 != $ROOTPASS2 ]]
+do
+    printf "ROOT password: "
+    read -s ROOTPASS1
+    printf "\n"
+    printf "ROOT password (Type again): "
+    read -s ROOTPASS2
+    printf "\n"
+    if [[ $ROOTPASS1 != $ROOTPASS2 ]]; then
+        echo "Password entered isn't the same. Try again!"
+    fi
+    if [[ $ROOTPASS1 == '' ]] || [[ $ROOTPASS2 == '' ]]; then
+        echo "ROOT password can't be empty!"
+    fi
+done
+
+echo -e "$ROOTPASS1\n$ROOTPASS2" | arch-chroot /mnt /bin/bash -c "passwd"
+
+while [[ $MYUSER1 == '' ]]
+do
+    read -p "Username: " MYUSER1
+done
+MYUSER=$(echo $MYUSER1 | tr -cd [:alnum:])
+
 echo "Добавим своего пользователя (меняем username на свое) и добавляем его в нужные группы"
 arch-chroot /mnt /bin/bash -c "useradd -m -k /etc/skel -g users -G audio,games,lp,optical,power,scanner,storage,video,wheel -s /bin/bash $MYUSER"
 echo "Установим пароль для нашего юзера"
-arch-chroot /mnt /bin/bash -c "passwd $MYUSER"
+while [[ $USERPASS1 == '' ]] || [[ $USERPASS2 == '' ]] || [[ $USERPASS1 != $USERPASS2 ]]
+do
+    printf "$MYUSER's password: "
+    read -s USERPASS1
+    printf "\n"
+    printf "$MYUSER's password (Type again): "
+    read -s USERPASS2
+    printf "\n"
+    if [[ $USERPASS1 != $USERPASS2 ]]; then
+        echo "Password entered isn't the same. Try again!"
+    fi
+    if [[ $USERPASS1 == '' ]] || [[ $USERPASS2 == '' ]]; then
+        echo "User's password can't be empty!"
+    fi
+done
+echo -e "$USERPASS1\n$USERPASS2" | arch-chroot /mnt /bin/bash -c "passwd $MYUSER"
+
 #Добавим ему информацию GECOS:
 arch-chroot /mnt /bin/bash -c "chfn victor3d"
 	
@@ -240,6 +283,7 @@ rm -dR /mnt/home/$MYUSER/bunsen-themes-git/
 # Вернем взад настройку pacman
 sed -i "s/#CheckSpace/CheckSpace/g" /mnt/etc/pacman.conf
 
+set -xe
 arch-chroot -u $MYUSER /mnt yaourt -S fetchmail obmenu i3-scrot ttf-paratype openbox-themes adeos-oblogout-git ttf-ms-fonts twmn-git --noconfirm
 
 echo "Все готово! Перезагрузись и кайфуй!"
